//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.УслугиВЗаказе = new HashSet<УслугиВЗаказе>();
        }
    
        public int ID { get; set; }
        public string НомерЗаказа { get; set; }
        public System.DateTime ДатаСоздания { get; set; }
        public int IDКлиента { get; set; }
        public string Статус { get; set; }
        public Nullable<System.DateTime> ДатаЗакрытия { get; set; }
        public Nullable<int> IDСотрудника { get; set; }
        public string ВремяВыполненияЗаказа { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<УслугиВЗаказе> УслугиВЗаказе { get; set; }
    }
}
