//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class КлиентЮЛ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public КлиентЮЛ()
        {
            this.Клиенты = new HashSet<Клиенты>();
        }
    
        public int ID { get; set; }
        public string НазваниеКомпании { get; set; }
        public string Адрес { get; set; }
        public string ИНН { get; set; }
        public string РС { get; set; }
        public string БИК { get; set; }
        public string ФИОРуководителя { get; set; }
        public string ФИОКонтЛица { get; set; }
        public string ТелефонКонтЛица { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Клиенты> Клиенты { get; set; }
    }
}
