//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Услуги
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Услуги()
        {
            this.УслугиВЗаказе = new HashSet<УслугиВЗаказе>();
            this.УслугиСотрудников = new HashSet<УслугиСотрудников>();
        }
    
        public int ID { get; set; }
        public string НаименованиеУслуги { get; set; }
        public string КодУслуги { get; set; }
        public string СрокВыполнения { get; set; }
        public string СреднееОтклонение { get; set; }
        public decimal Стоимость { get; set; }
        public decimal СтоимостьЗАОРусКосм { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<УслугиВЗаказе> УслугиВЗаказе { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<УслугиСотрудников> УслугиСотрудников { get; set; }
    }
}
