//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class УслугиВЗаказе
    {
        public int ID { get; set; }
        public int IDЗаказа { get; set; }
        public int IDУслуги { get; set; }
        public int IDСтатуса { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        public virtual СтатусУслугиВЗаказе СтатусУслугиВЗаказе { get; set; }
        public virtual Услуги Услуги { get; set; }
    }
}
